### PR TITLE
Fix : Wrong pagination for platform filter in member detail page 

### LINKED ISSUE #990: [C-1633] [C-1632] Wrong pagination for platform filter in member detail page
Steps to reproduce:

* Go to a member detail page that has more than 10 activities and in more than one platform
* On the Activities tab of that page click on Load more button to load more activities in the timeline
* We will now show 20 activities (limit: 20, offset: 20)
* If we filter this timeline by selecting another platform in the select platform, we maintain the previous pagination (limit: 20, offset: 20) instead of resetting these values. So it might happen that the user sees nothing in the timeline

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1632](https://linear.app/crowddotdev/issue/C-1632/wrong-pagination-for-platform-filter-in-member-detail-page)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1632](https://linear.app/crowddotdev/issue/C-1632/wrong-pagination-for-platform-filter-in-member-detail-page)</sub>

### PR DESCRIPTION
**Pull request by Dhruwang**
# Changes proposed ✍️

Fixes #990 

### What

When platform changes, offset value was not getting reset thus user was not able to see all activities

### How
Set offset to 0 when platform value changes 

### <samp>🤖 Generated by Copilot at ec363a4</samp>

* Reset offset value to zero on component creation to fetch most recent activities ([link](https://github.com/CrowdDotDev/crowd.dev/pull/1023/files?diff=unified&w=0#diff-ac35928641997d2be2d0c43afd02a85bf32a2b169074ac40ddcad8b21477eaf8R322))

## Checklist ✅
- [x] Label appropriately with `Feature`, `Improvement`, or `Bug`.
- [x] Add screehshots to the PR description for relevant FE changes
- [x] New backend functionality has been unit-tested.
- [x] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [x] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

### CODE REVIEW

File: frontend/src/modules/activity/components/activity-timeline.vue [hunk 1]
```diff
@@ -319,6 +319,7 @@ watch(query, (newValue, oldValue) => {
 
 watch(platform, async (newValue, oldValue) => {
   if (newValue !== oldValue) {
+    offset.value = 0
```
Comment (joanagmaia) [inline frontend/src/modules/activity/components/activity-timeline.vue:322]: This line fixes the described issue. However, I think it might be better to add it on line 265 which is where we have the logic to reset the request
So it would be 
```
  if (!isEqual(filter, filterToApply)) {
    activities.length = 0;
    offset.value = 0
    noMore.value = false;
  }
```
When platform changes the fetch method enters this condition and resets the values. Could you please make this change?

**Review by joanagmaia — CHANGES_REQUESTED** [review]
Hey 😄 Thanks for picking this one up! Requested a change so that the fix is made on the fetch method instead of the watcher

**Comment by Dhruwang** [comment]
@joanagmaia Can you check now ?

**Review by joanagmaia — APPROVED** [review]
LGTM 🚀
